# /etc/keyd/default.conf

[ids]
*

[main]
# capslock = timeout(esc, 200, capslock)

# for my keyboard with volume knob
[control]
volumeup = down
volumedown = up

[shift]
volumeup = C-equal
volumedown = C-minus

[alt]
volumeup = brightnessup
volumedown = brightnessdown
