# Syntax highlighting
# -------------------
"attribute" = { fg = "blue", modifiers = ["italic"] }

"keyword" = { fg = "gray2", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "water", modifiers = ["bold"] }
"keyword.directive" = { fg = "coral", modifiers = ["bold"] }

"namespace" = { fg = "teal", modifiers = ["italic"] }

"punctuation" = { fg = "gray2" }
"punctuation.delimiter" = { fg = "gray2" }
"operator" = { fg = "blue" }
"special" = { fg = "violet", modifiers = ["bold"] }

"variable" = { fg = "white" }
"variable.builtin" = { fg = "gold", modifiers = ["italic"] }
"variable.parameter" = { fg = "gray1", modifiers = ["italic"] }
"variable.other.member" = { fg = "gray1" }

"type" = { fg = "yellow", modifiers = ["bold"] }
"type.builtin" = { fg = "yellow", modifiers = ["bold", "italic"] }
"type.enum.variant" = { fg = "gold" }

"constructor" = { fg = "water" }

"function" = { fg = "coral" }
"function.macro" = { fg = "coral", modifiers = ["bold"] }
"function.builtin" = { fg = "cyan", modifiers = ["italic"] }
"function.method" = { fg = "coral", modifiers = ["italic"] }

"tag" = { fg = "violet" }

"comment" = { fg = "green", modifiers = ["italic"] }

"string" = { fg = "gold" }
"string.regexp" = { fg = "teal", modifiers = ["italic"] }
"string.special" = { fg = "violet", modifiers = ["bold"] }

"constant" = { fg = "purple" }
"constant.builtin" = { fg = "purple", modifiers = ["bold"] }
"constant.numeric" = { fg = "purple" }
"constant.character.escape" = { fg = "gold", modifiers = ["bold"] }

"label" = { fg = "water" }

"markup.heading" = { fg = "gold", modifiers = ["bold"] }
"markup.list" = { fg = "water" }
"markup.link" = { fg = "blue", modifiers = ["underlined"] }
"markup.link.url" = { fg = "teal", modifiers = ["underlined"] }
"markup.raw" = { fg = "cyan", bg = "bg1" }
"markup.quote" = { fg = "violet", bg = "bg1", modifiers = ["italic"] }

"diff.plus" = { fg = "teal", modifiers = ["bold"] }
"diff.minus" = { fg = "coral", modifiers = ["bold"] }
"diff.delta" = { fg = "gold", modifiers = ["bold"] }


# User Interface
# --------------
"ui.background" = { fg = "white", bg = "bgm" }
"ui.background.separator" = { fg = "gray3" }

"ui.bufferline" = { fg = "white", bg = "gray3" }
"ui.bufferline.active" = { fg = "bg2", bg = "white", modifiers = ["bold"] }
"ui.bufferline.background" = { bg = "bg2"}

"ui.menu" = { fg = "white", bg = "bg2" }
"ui.menu.selected" = { fg = "bg2", bg = "white", modifiers = ["bold"] }
"ui.menu.scroll" = { fg = "white", bg = "bg2" }

"ui.statusline" = { fg = "white", bg = "bg2" }
"ui.statusline.inactive" = { fg = "gray3", bg = "bg2" }
"ui.statusline.normal" = { fg = "bg1", bg = "gold", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg1", bg = "coral", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg1", bg = "teal", modifiers = ["bold"] }

"ui.popup" = { fg = "white", bg = "bg2" }
"ui.popup.info" = { fg = "white", bg = "bg2" }
"ui.window" = { fg = "gray3" }
"ui.help" =  { fg = "white", bg = "bg1" }

"ui.text" = { fg = "white" }
"ui.text.inactive" = { fg = "gray2" }
"ui.text.focus" = { fg = "gray1", modifiers = ["bold"] }
"ui.text.info" = { fg = "water"}

"ui.virtual.ruler" = { bg = "bg2" }
"ui.virtual.indent-guide" = { fg = "gray4" }
"ui.virtual.inlay-hint" = { fg = "gray3", modifiers = ["italic"] }
"ui.virtual.space" = { fg = "gray4" }
"ui.virtual.wrap" = { fg = "gray4" }

"ui.selection" = { bg = "bg2" }
"ui.selection.primary" = { bg = "gray3" }

"ui.cursor" = { fg = "bg1", bg = "white" }
"ui.cursor.insert" = { fg = "bg1", bg = "coral" }
"ui.cursor.select" = { fg = "bg1", bg = "gold" }
"ui.cursor.match" = { fg = "gold", bg = "gray1", modifiers = ["bold", "underlined"] }
"ui.cursor.primary" = { fg = "bg1", bg = "white" }

"ui.linenr" = { fg = "gray2" }
"ui.linenr.selected" = { fg = "white", modifiers = ["bold"] }

"ui.cursorline.primary" = { bg = "bg2" }

"ui.highlight" = { bg = "gray3" }

"diagnostic" = { modifiers = ["underlined"] }

"error" = { fg = "err", modifiers = ["bold", "underlined"] }
"warning" = { fg = "warn", modifiers = ["bold"] }
"info" = { fg = "water" }
"hint" = { fg = "hint" }

[palette]




white = "#F8F9FA"       # Primary text, variables
gray1 = "#ADB5BD"       # Member variables, secondary text, punctuation, delimiters
gray2 = "#6C757D"       # Functions, Line numbers
gray3 = "#495057"       #
gray4 = "#343A40"       # Subtle UI elements
bg2 = "#1a1a1a"         # Selection backgrounds
bg1 = "#0f0f0f"         # Subtle dark for UI elements
bgm = "#000000"         # Pure black background

blue = "#0096c7"        # Attributes, operators
water = "#48cae4"       # Parameters, constructors, conditionals

cyan = "#005F73"        # Built-in variable, built-in function
teal = "#0A9396"        # Namespaces, special, regex
tiffany = "#5bc0be"     # Strings
gold = "#E9D8A6"        #
yellow = "#fcbf49"      # Types, built-in types
coral = "#f77f00"       # Macros, directives, funtions, methods
orange = "#BB3E03"      # Keywords (fn, let, match, use, as, mod, async, impl)

purple = "#C77DFF"      # Constants, numbers
violet = "#E0AAFF"      # Tags, special strings


# my ui colors
white = "#F8F9FA"

gray1 = "#ADB5BD"
gray2 = "#6C757D"
gray3 = "#495057"
gray4 = "#343A40"

pur1 = "#9d4edd"
pur2 = "#7b2cbf"
pur3 = "#5a189a"
pur4 = "#3c096c"
pur5 = "#240046"
pur6 = "#10002b"

bgm = "#070012"

green = "#40916c"

err = "#ff0004"
warn = "#ffff00"
hint = "#009dff"


