# SYNTAX
"attribute"                 = "white"            #
"comment"                   = "dark_green"       #

"constant"                  = "pale_green"
"constant.builtin"          = "blue"
"constant.character"        = "orange"
"constant.character.escape" = "gold"
"constant.numeric"          = "pale_green"

"constructor"               = "type"            #

"diff.plus"                 = "dark_green"      #
"diff.minus"                = "orange_red"      #
"diff.delta"                = "blue"            #

"function"                  = "fn_declaration"  #
"function.builtin"          = "fn_declaration"  #
"function.macro"            = "water"           #

"keyword"                   = "gold"            # ?

"label"                     = "blue"

"module"                    = "type"

"namespace"                 = "blue"

"operator"                  = "white"           #

"punctuation"               = "gray1"           #
"punctuation.delimiter"     = "gray1"           #

"special"                   = "light_blue"
"string"                    = "gold"
"string.regexp"             = "gold"
"tag"                       = "blue"

"type"                      = "type"            #
"type.enum.variant"         = "constant"

"variable"                  = "white"           #
"variable.builtin"          = "blue"            #
"variable.other.member"     = "gray1"           #
"variable.parameter"        = {fg = "white", modifiers = ["italic"]}            #

# MARKUP
"markup.heading"       = { fg = "blue", modifiers = ["bold"] }
"markup.list"          = "blue"
"markup.bold"          = { modifiers = ["bold"] }
"markup.italic"        = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url"      = { underline.style= "line" }
"markup.link.text"     = "orange"
"markup.quote"         = "dark_green"
"markup.raw"           = "orange"

# UI
"ui.background"              = { fg = "white", bg = "bg" }
"ui.window"                  = { bg = "widget" }

"ui.popup"                   = { fg = "widget_text", bg = "widget" }
"ui.help"                    = { fg = "widget_text", bg = "widget" }
"ui.menu"                    = { fg = "white", bg = "widget" }
"ui.menu.selected"           = { fg = "bg", bg = "select", modifiers = ["bold"] }

"ui.statusline"              = { fg = "white", bg = "widget" }
"ui.statusline.inactive"     = { fg = "white", bg = "widget" }
"ui.statusline.insert"       = { fg = "white", modifiers = ["reversed", "bold"] }
"ui.statusline.select"       = { fg = "bg", bg = "select", modifiers = ["bold"] }

"ui.bufferline"              = { fg = "white", bg = "uselect" }
"ui.bufferline.active"       = { fg = "bg", bg = "select", modifiers = ["bold"] }
"ui.bufferline.background"   = { bg = "widget" }

"ui.cursor"                  = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.primary"          = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match"            = { bg = "gray3", underline.style = "line" }

"ui.selection"               = { bg = "#3a3d41" }
"ui.selection.primary"       = { bg = "gray4" }

"ui.linenr"                  = { fg = "gray3" }
"ui.linenr.selected"         = { fg = "gray1" }

"ui.cursorline.primary"      = { bg = "gray5" }

"ui.text"                    = { fg = "white" }
"ui.text.focus"              = { fg = "gray1" }
"ui.text.directory"          = { fg = "gray2" }
"ui.text.inactive"           = { fg = "gray3" }

"ui.virtual.whitespace"      = { fg = "#3e3e3d" }
"ui.virtual.wrap"            = { fg = "#3e3e3d" }
"ui.virtual.ruler"           = { bg = "gray5" }
"ui.virtual.indent-guide"    = { fg = "gray4" }
"ui.virtual.inlay-hint"      = { fg = "gray3"}
"ui.virtual.jump-label"      = { fg = "yellow", modifiers = ["bold"] }

"ui.highlight.frameline"     = { bg = "#4b4b18" }

"ui.debug.active"            = { fg = "#ffcc00" }
"ui.debug.breakpoint"        = { fg = "#e51400" }

"ui.picker.header.column"    = { underline.style = "line" }
"ui.picker.header.column.active" = { fg ="white", underline.style = "line" }

"warning"                    = { fg = "gold2" }
"error"                      = { fg = "red" }
"info"                       = { fg = "light_blue" }
"hint"                       = { fg = "white" }             # ?

"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic".underline       = { color = "gold", style = "curl" }
"diagnostic.unnecessary"     = { modifiers = ["dim"] }
"diagnostic.deprecated"      = { modifiers = ["crossed_out"] }

[palette]
orange = "#ce9178"
gold = "#d7ba7d"
gold2 = "#cca700"
pale_green = "#b5cea8"
dark_green = "#6A9955"
light_blue = "#75beff"
red = "#ff1212"
orange_red = "#f14c4c"
type = "#fcbf49"
special = "#5bc0be"
fn_declaration = "#6C757D"
constant = "#f77f00"

# my ui colors

blue = "#0096c7"
water = "#48cae4"

white = "#F8F9FA"

gray1 = "#ADB5BD"
gray2 = "#6C757D"
gray3 = "#495057"
gray4 = "#343A40"
gray5 = "#212529"

widget_text = "#c77dff"
select = "#9d4edd"
uselect = "#240046"
widget = "#10002b"
bg = "#000000"


