inherits = "rose_pine"

# SYNTAX
"comment" = { fg = "highlight_high", modifiers = ["italic"] }

# UI
"ui.background" = {}
"ui.cursor" = { fg = "text", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "text", modifiers = ["reversed", "bold"] }

"ui.statusline.normal" = { fg = "base", bg = "rose", modifiers = ["reversed", "bold"] }
"ui.statusline.insert" = { fg = "foam", bg = "base", modifiers = ["reversed", "bold"] }
"ui.statusline.select" = { fg = "iris", bg = "base", modifiers = ["reversed", "bold"] }

"ui.bufferline" = { fg = "subtle", bg = "base" }
"ui.bufferline.active" = { fg = "base", bg = "subtle", modifiers = ["bold"] }

"ui.virtual.indent-guide" = { fg = "highlight_med" }
