theme = "rose_chad"

[editor]
line-number = "relative"
cursorline = true
bufferline = "always"
color-modes = true
text-width = 100
auto-format = true
auto-save = true
rulers = [100]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # Show inline diagnostics when the cursor is on the line
# other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 0

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# lazygit
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# yazi file picker
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
# move/copy line below/above
A-j = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
A-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-J = [ "extend_to_line_bounds", "yank", "paste_after" ]
A-K = [ "extend_to_line_bounds", "yank", "paste_before" ]
# previous/next buffer
H = "goto_previous_buffer"
L = "goto_next_buffer"
A-q = ":buffer-close"

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.insert]
C-c = "signature_help"
