[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh", "cppm", "h++", "ii", "inl", { glob = ".hpp.in" }, { glob = ".h.in" }]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = [ "clangd" ]
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"

[[language]]
name = "lua"
formatter = { command = "stylua", args = [ "-" ] }
auto-format = true

[language-server.tinymist]
command = "tinymist"
config.exportPdf = "onSave"
config.preview.background.enabled = true
config.preview.background.args = [
  "--data-plane-host=127.0.0.1:0", "--invert-colors=never", "--open"]
