[[language]]
name="rust"

[language.config]
checkOnSave = {command = "clippy"}
cargo = {allFeatures = true}
procMacro = {enable = true }
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language-server.rust-analyzer.config.cargo]
features = "all"


